// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.1
// source: doubleGift.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetInfoReq) Reset() {
	*x = GetInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_doubleGift_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoReq) ProtoMessage() {}

func (x *GetInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_doubleGift_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoReq.ProtoReflect.Descriptor instead.
func (*GetInfoReq) Descriptor() ([]byte, []int) {
	return file_doubleGift_proto_rawDescGZIP(), []int{0}
}

type GetInfoRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GoldNum int32 `protobuf:"varint,1,opt,name=gold_num,json=goldNum,proto3" json:"gold_num,omitempty"`
}

func (x *GetInfoRes) Reset() {
	*x = GetInfoRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_doubleGift_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetInfoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRes) ProtoMessage() {}

func (x *GetInfoRes) ProtoReflect() protoreflect.Message {
	mi := &file_doubleGift_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRes.ProtoReflect.Descriptor instead.
func (*GetInfoRes) Descriptor() ([]byte, []int) {
	return file_doubleGift_proto_rawDescGZIP(), []int{1}
}

func (x *GetInfoRes) GetGoldNum() int32 {
	if x != nil {
		return x.GoldNum
	}
	return 0
}

type ExchangeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Idx int32 `protobuf:"varint,1,opt,name=idx,proto3" json:"idx,omitempty"`
}

func (x *ExchangeReq) Reset() {
	*x = ExchangeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_doubleGift_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExchangeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeReq) ProtoMessage() {}

func (x *ExchangeReq) ProtoReflect() protoreflect.Message {
	mi := &file_doubleGift_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeReq.ProtoReflect.Descriptor instead.
func (*ExchangeReq) Descriptor() ([]byte, []int) {
	return file_doubleGift_proto_rawDescGZIP(), []int{2}
}

func (x *ExchangeReq) GetIdx() int32 {
	if x != nil {
		return x.Idx
	}
	return 0
}

type ExchangeRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gotten int32 `protobuf:"varint,1,opt,name=gotten,proto3" json:"gotten,omitempty"`
}

func (x *ExchangeRes) Reset() {
	*x = ExchangeRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_doubleGift_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExchangeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeRes) ProtoMessage() {}

func (x *ExchangeRes) ProtoReflect() protoreflect.Message {
	mi := &file_doubleGift_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeRes.ProtoReflect.Descriptor instead.
func (*ExchangeRes) Descriptor() ([]byte, []int) {
	return file_doubleGift_proto_rawDescGZIP(), []int{3}
}

func (x *ExchangeRes) GetGotten() int32 {
	if x != nil {
		return x.Gotten
	}
	return 0
}

var File_doubleGift_proto protoreflect.FileDescriptor

var file_doubleGift_proto_rawDesc = []byte{
	0x0a, 0x10, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x47, 0x69, 0x66, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x0c, 0x0a, 0x0a, 0x47,
	0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x22, 0x27, 0x0a, 0x0a, 0x47, 0x65, 0x74,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x6f, 0x6c, 0x64, 0x5f,
	0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x67, 0x6f, 0x6c, 0x64, 0x4e,
	0x75, 0x6d, 0x22, 0x1f, 0x0a, 0x0b, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65,
	0x71, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x69, 0x64, 0x78, 0x22, 0x25, 0x0a, 0x0b, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52,
	0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x6f, 0x74, 0x74, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x67, 0x6f, 0x74, 0x74, 0x65, 0x6e, 0x32, 0x41, 0x0a, 0x07, 0x47, 0x65,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x36, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x70, 0x63, 0x12, 0x13, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x47, 0x65,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x32, 0x45, 0x0a,
	0x08, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x39, 0x0a, 0x0b, 0x45, 0x78, 0x63,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x70, 0x63, 0x12, 0x14, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x14,
	0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x52, 0x65, 0x73, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_doubleGift_proto_rawDescOnce sync.Once
	file_doubleGift_proto_rawDescData = file_doubleGift_proto_rawDesc
)

func file_doubleGift_proto_rawDescGZIP() []byte {
	file_doubleGift_proto_rawDescOnce.Do(func() {
		file_doubleGift_proto_rawDescData = protoimpl.X.CompressGZIP(file_doubleGift_proto_rawDescData)
	})
	return file_doubleGift_proto_rawDescData
}

var file_doubleGift_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_doubleGift_proto_goTypes = []interface{}{
	(*GetInfoReq)(nil),  // 0: message.GetInfoReq
	(*GetInfoRes)(nil),  // 1: message.GetInfoRes
	(*ExchangeReq)(nil), // 2: message.ExchangeReq
	(*ExchangeRes)(nil), // 3: message.ExchangeRes
}
var file_doubleGift_proto_depIdxs = []int32{
	0, // 0: message.GetInfo.GetInfoRpc:input_type -> message.GetInfoReq
	2, // 1: message.Exchange.ExchangeRpc:input_type -> message.ExchangeReq
	1, // 2: message.GetInfo.GetInfoRpc:output_type -> message.GetInfoRes
	3, // 3: message.Exchange.ExchangeRpc:output_type -> message.ExchangeRes
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_doubleGift_proto_init() }
func file_doubleGift_proto_init() {
	if File_doubleGift_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_doubleGift_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_doubleGift_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetInfoRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_doubleGift_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExchangeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_doubleGift_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExchangeRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_doubleGift_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_doubleGift_proto_goTypes,
		DependencyIndexes: file_doubleGift_proto_depIdxs,
		MessageInfos:      file_doubleGift_proto_msgTypes,
	}.Build()
	File_doubleGift_proto = out.File
	file_doubleGift_proto_rawDesc = nil
	file_doubleGift_proto_goTypes = nil
	file_doubleGift_proto_depIdxs = nil
}
