// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.1
// source: doubleGift.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GetInfoClient is the client API for GetInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetInfoClient interface {
	GetInfoRpc(ctx context.Context, in *GetInfoReq, opts ...grpc.CallOption) (*GetInfoRes, error)
}

type getInfoClient struct {
	cc grpc.ClientConnInterface
}

func NewGetInfoClient(cc grpc.ClientConnInterface) GetInfoClient {
	return &getInfoClient{cc}
}

func (c *getInfoClient) GetInfoRpc(ctx context.Context, in *GetInfoReq, opts ...grpc.CallOption) (*GetInfoRes, error) {
	out := new(GetInfoRes)
	err := c.cc.Invoke(ctx, "/message.GetInfo/GetInfoRpc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetInfoServer is the server API for GetInfo service.
// All implementations must embed UnimplementedGetInfoServer
// for forward compatibility
type GetInfoServer interface {
	GetInfoRpc(context.Context, *GetInfoReq) (*GetInfoRes, error)
	mustEmbedUnimplementedGetInfoServer()
}

// UnimplementedGetInfoServer must be embedded to have forward compatible implementations.
type UnimplementedGetInfoServer struct {
}

func (UnimplementedGetInfoServer) GetInfoRpc(context.Context, *GetInfoReq) (*GetInfoRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInfoRpc not implemented")
}
func (UnimplementedGetInfoServer) mustEmbedUnimplementedGetInfoServer() {}

// UnsafeGetInfoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetInfoServer will
// result in compilation errors.
type UnsafeGetInfoServer interface {
	mustEmbedUnimplementedGetInfoServer()
}

func RegisterGetInfoServer(s grpc.ServiceRegistrar, srv GetInfoServer) {
	s.RegisterService(&GetInfo_ServiceDesc, srv)
}

func _GetInfo_GetInfoRpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetInfoServer).GetInfoRpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.GetInfo/GetInfoRpc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetInfoServer).GetInfoRpc(ctx, req.(*GetInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

// GetInfo_ServiceDesc is the grpc.ServiceDesc for GetInfo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetInfo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "message.GetInfo",
	HandlerType: (*GetInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfoRpc",
			Handler:    _GetInfo_GetInfoRpc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "doubleGift.proto",
}

// ExchangeClient is the client API for Exchange service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExchangeClient interface {
	ExchangeRpc(ctx context.Context, in *ExchangeReq, opts ...grpc.CallOption) (*ExchangeRes, error)
}

type exchangeClient struct {
	cc grpc.ClientConnInterface
}

func NewExchangeClient(cc grpc.ClientConnInterface) ExchangeClient {
	return &exchangeClient{cc}
}

func (c *exchangeClient) ExchangeRpc(ctx context.Context, in *ExchangeReq, opts ...grpc.CallOption) (*ExchangeRes, error) {
	out := new(ExchangeRes)
	err := c.cc.Invoke(ctx, "/message.Exchange/ExchangeRpc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExchangeServer is the server API for Exchange service.
// All implementations must embed UnimplementedExchangeServer
// for forward compatibility
type ExchangeServer interface {
	ExchangeRpc(context.Context, *ExchangeReq) (*ExchangeRes, error)
	mustEmbedUnimplementedExchangeServer()
}

// UnimplementedExchangeServer must be embedded to have forward compatible implementations.
type UnimplementedExchangeServer struct {
}

func (UnimplementedExchangeServer) ExchangeRpc(context.Context, *ExchangeReq) (*ExchangeRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExchangeRpc not implemented")
}
func (UnimplementedExchangeServer) mustEmbedUnimplementedExchangeServer() {}

// UnsafeExchangeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExchangeServer will
// result in compilation errors.
type UnsafeExchangeServer interface {
	mustEmbedUnimplementedExchangeServer()
}

func RegisterExchangeServer(s grpc.ServiceRegistrar, srv ExchangeServer) {
	s.RegisterService(&Exchange_ServiceDesc, srv)
}

func _Exchange_ExchangeRpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExchangeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExchangeServer).ExchangeRpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Exchange/ExchangeRpc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExchangeServer).ExchangeRpc(ctx, req.(*ExchangeReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Exchange_ServiceDesc is the grpc.ServiceDesc for Exchange service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Exchange_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "message.Exchange",
	HandlerType: (*ExchangeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExchangeRpc",
			Handler:    _Exchange_ExchangeRpc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "doubleGift.proto",
}
